const Data = [
    {
    name: "Canada",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/can.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#d52b1e",
    secondary : "#ff6b5c",
    players: [
      {
        name: "Bin Zafar",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Johnson",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Heyliger",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bajwa",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Thaker",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Gordon",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Siddiqui",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Sana",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Tathgur",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Dhaliwal",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kirton",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Ireland",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/ire.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#30763a",
    secondary : "#5fbf6b",
    players: [
      {
        name: "Adair",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Stirling",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Tector",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Balbirnie",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Tucker",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Dockrell",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Delany",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Adair",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "McCarthy",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Little",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "White",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Namibia",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/nam.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#003f8a",
    secondary : "#3f8fff",
    players: [
      {
        name: "Frylinck",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kruger",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Loftie-Eaton",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Erasmus",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Wiese",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Green",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Trumpelmann",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Balt",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Scholtz",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shikongo",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Heingo",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Nepal",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/nep.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#3399ff",
    secondary : "#80c1ff",
    players: [
      {
        name: "Paudel",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Sheikh",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bhurtel",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Malla",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Airee",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Lamichhane",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Jora",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "KC",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rajbanshi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kami",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Alam",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Oman",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/oma.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#df1a23",
    secondary : "#ff5c61",
    players: [
      {
        name: "Prajapati",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Athavale",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ilyas",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Maqsood",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kail",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Khan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Butt",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shoaib",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ayaan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Zeeshan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kaleemullah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Scotland",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/sco.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#0572c4",
    secondary : "#66b9ff",
    players: [
      {
        name: "Munsey",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Hairs",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Berrington",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "McMullen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Leask",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Cross",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Greaves",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Sharif",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Watt",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Cassell",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Wheal",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "UAE",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/uae.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#cacaca",
    secondary : "#ffffff",
    players: [
      {
        name: "Waseem",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Sharafu",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Sharma",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Khan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Parashar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "D’Souza",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ali",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kaushik",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Siddique",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Zohaib",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Chopra",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "USA",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/usa.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#bb133e",
    secondary : "#ff7b9b",
    players: [
      {
        name: "Patel",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Gous",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Jones",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Taylor",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Anderson",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Singh",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Khan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kenjige",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Netravalkar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Harmeet",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ali",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Zimbabwe",
    category: "Bronze",
    score: 0,
    wicket: 0,
    flag: "/img/zim.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#ffd200",
    secondary : "#fff27a",
    players: [
      {
        name: "Marumani",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Madhevere",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "S Raza",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Burl",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bennett",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Munyonga",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Masakadza",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Akram",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Gwandu",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ngarava",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Muzarabani",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "Afghanistan",
    category: "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/afg.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#4497d4",
    secondary : "#7cc0ff",
    players: [
      {
        name: "Gurbaz",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "H Zazai",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "N Zadran",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rahmanullah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shehzad",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Janat",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rashid",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Gulbadin",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Nabi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Mujeeb",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Naveen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Bangladesh",
    category: "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/ban.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#006b4f",
    secondary : "#2dd59b",
    players: [
      {
        name: "Liton",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Tamim",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Mushfiqur",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Afif",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Naim",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Mahmudullah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shakib",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Mehidy",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Taskin",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Mustafizur",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shoriful",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Netherlands",
    category: "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/net.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#ff8533",
    secondary : "#ffb366",
    players: [
      {
        name: "O’Dowd",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Levitt",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Vikramjit",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Nidamanuru",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Edwards",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Noah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Zulfiqar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Aryan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Klein",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Meekeren",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Klaassen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "West Indies",
    category: "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/wi.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#9c1444",
    secondary : "#e04b7f",
    players: [
      {
        name: "Hope",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "King",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Hetmyer",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rutherford",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Pooran",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Chase",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Holder",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "A Hosein",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "A Joseph",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shepherd",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Blades",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "New Zealand",
    category: "Gold",
    score: 0,
    wicket: 0,
    flag: "/img/nz.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#111018", //#555555
    secondary : "#888888",
    players: [
      {
        name: "F Allen",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Conway",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Williamson",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Phillips",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Mitchell",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Neesham",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Santner",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Southee",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ferguson",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Boult",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Sodhi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "South Africa",
    category: "Gold",
    score: 0,
    wicket: 0,
    flag: "/img/sa.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#007847",
    secondary : "#26d98a",
    players: [
      {
        name: "De kock",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Markram",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bavuma",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Dussen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Klassen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Miller",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Jansen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shamsi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rabada",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Nortje",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Ngidi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "Sri Lanka",
    category: "Gold",
    score: 0,
    wicket: 0,
    flag: "/img/sri.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#0e306f",
    secondary : "#163c8c",
    players: [
      {
        name: "K Mendis",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Nissanka",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Asalanka",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Shanaka",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Chandimal",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rajapaksa",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Hasaranga",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Karunaratne",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Theekshana",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Madushanka",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kumara",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "Australia",
    category: "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/aus.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#c1ab11",
    secondary : "#fde505",
    players: [
      {
        name: "Head",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Marsh",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Smith",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Labuschagne",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "T David",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Carey",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Maxwell",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Cummins",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Zampa",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Hazlewood",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Starc",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "England",
    category: "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/eng.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#2d91be",
    secondary : "#6fc8f1",
    players: [
      {
        name: "Duckett",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Buttler",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Root",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bairstow",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "LivingStone",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Brook",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Stokes",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Moeen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rashid",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Wood",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Archer",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
  {
    name: "India",
    category: "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/ind.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#ff9933",
    secondary : "#ffc266",
    players: [
      {
        name: "Rohit",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rahul",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kohli",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Suryakumar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Pant",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Pandya",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Jadeja",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Kuldeep",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Arshdeep",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Siraj",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bumrah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
    {
    name: "Pakistan",
    category: "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/pak.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    primary : "#01411c",
    secondary : "#03a65a",
    players: [
      {
        name: "Babar",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Bilal",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Fakhar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "H Nawaz",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Rizwan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Iftikhar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Nawaz",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Afridi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Wasim jr",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Abrar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
      {
        name: "Naseem",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.0,
        conceded: 0,
      },
    ],
  },
];

export default Data;
