
const Data = [
              {
    name: "Afghanistan",
    category : "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/afg.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Gurbaz",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "H Zazai",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "N Zadran",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rahmanullah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Shehzad",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Janat",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rashid",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Gulbadin",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Nabi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Mujeeb",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Naveen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
    {
    name: "Australia",
    category : "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/aus.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Head",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Marsh",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Smith",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Labuschagne",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "T David",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Carey",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Maxwell",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Cummins",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Zampa",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Hazlewood",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Starc",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
                {
    name: "Bangladesh",
    category : "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/ban.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Liton",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Tamim",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Mushfiqur",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Afif",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Naim",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Mahmudullah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Shakib",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Mehidy",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Taskin",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Mustafizur",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Shoriful",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
      {
    name: "England",
    category : "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/eng.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Duckett",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Buttler",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Root",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Bairstow",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "LivingStone",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Brook",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Stokes",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Moeen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rashid",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Wood",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Archer",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
    {
    name: "India",
    category : "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/ind.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Rohit",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rahul",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Kohli",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Suryakumar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Pant",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Pandya",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Jadeja",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Kuldeep",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Arshdeep",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Siraj",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Bumrah",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
        {
    name: "New Zealand",
    category : "Gold",
    score: 0,
    wicket: 0,
    flag: "/img/nz.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "F Allen",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Conway",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Williamson",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Phillips",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Mitchell",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Neesham",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Santner",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Southee",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Ferguson",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Boult",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Sodhi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
  {
    name: "Pakistan",
    category : "Legendary",
    score: 0,
    wicket: 0,
    flag: "/img/pak.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Babar",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Bilal",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Fakhar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "H Nawaz",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rizwan",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Iftikhar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Nawaz",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Afridi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Wasim jr",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Abrar",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Naseem",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
        {
    name: "South Africa",
    category : "Gold",
    score: 0,
    wicket: 0,
    flag: "/img/sa.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "De kock",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Markram",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Bavuma",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Der Dussen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Klassen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Miller",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Jansen",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Shamsi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rabada",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Nortje",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Ngidi",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
          {
    name: "Sri Lanka",
    category : "Gold",
    score: 0,
    wicket: 0,
    flag: "/img/sri.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "K Mendis",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Nissanka",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Asalanka",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Shanaka",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Chandimal",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rajapaksa",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Hasaranga",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Karunaratne",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Theekshana",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Madushanka",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Kumara",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
                {
    name: "West Indies",
    category : "Silver",
    score: 0,
    wicket: 0,
    flag: "/img/wi.png",
    Over: 0,
    Ball: 0,
    ballHistory: [],
    fow: [],
    players: [
      {
        name: "Hope",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: true,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "King",
        score: 0,
        balls: 0,
        out: false,
        notout: true,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Hetmyer",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Rutherford",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Pooran",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Chase",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: false,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Holder",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "A Hosein",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "A Joseph",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Shepherd",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
      {
        name: "Blades",
        score: 0,
        balls: 0,
        out: false,
        notout: false,
        striker: false,
        isBowler: true,
        bowler: null,
        wickets: 0,
        dot: 0,
        overs: 0,
        bowled: 0,
        economy: 0.00,
        conceded: 0,
      },
    ],
  },
];

export default Data;
